### ISSUE TITLE
reunite with caravan owner makes all animals in the caravan to keep following it . 

### ISSUE THREAD

**Issue by abmpicoli2** [SlavRim/WeAreUnited#3]
@MIS42NE very interesting mod! That said, I think I've just found a bug. A trade caravan got this guy Villegas ( trader ) as the son of Maverick (my colonist). She asked him to reunite and YAY! Her son joined the colony...

Detail: the caravan did have animals. And the caravan has all animals with the order follow villegas :D . Right now I have 2 muffalos and an Aurora Sylph following Villegas to the bathroom :D . And sh*tting EVERYWHERE :D 

The screenshot (steam removes the link... had to replace with spaces ... https: // snipboard.io / pJFwIj.jpg 

![image](https://github.com/SlavRim/WeAreUnited/assets/37077317/4375e093-d1d4-449f-b706-cc5d90a61a08)

**Comment by abmpicoli2** [comment]
hugslib gist https://gist.github.com/HugsLibRecordKeeper/51de17707949c9b39aed5877d5b3c59e

**Comment by abmpicoli2** [comment]
[ISSUE_3_SAVE.zip](https://github.com/SlavRim/WeAreUnited/files/13196543/ISSUE_3_SAVE.zip)
The save file, compacted.

**Comment by Sl4vP0weR** [comment]
Can you please make save file with the bug, but with minimal mod list and before the pawns were united?

**Comment by Sl4vP0weR** [comment]
In my test-case there was a trader of caravan and after reunion, caravan animals didn't follow the trader.

**Comment by Sl4vP0weR** [comment]
None feedback was provided, closing.
